runtime: python39

env_variables:
  BOOKIPLY_API_Key: $BOOKIPLY_API_KEY
  fa_API_KEY: $FA_API_KEY
  Flask_Secret_Key_FEWO: $Flask_Secret_Key_FEWO

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto