# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: 73h/gae-app-yaml-replace-env-variables@v0.3
      env:
        BOOKIPLY_API_KEY: ${{ secrets.BOOKIPLY_API_KEY }}
        FA_API_KEY: ${{ secrets.FA_API_KEY }}
        Flask_Secret_Key_FEWO: ${{ secrets.Flask_Secret_Key_FEWO }}
      with:
        app_yaml_path: "app.yaml"
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}